name: mercado_pago_ducos
description: "Mercado Pago implementation with SDK"
version: 0.0.1
homepage: https://github.com/santiagoduc0s/mercado_pago_ducos

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
